services:
  gunicorn:
    build:
      context: .
      dockerfile: gunicorn/Dockerfile
    # ports:
    #   - "5000:5000"

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8000:80"
